/**
 * ObjectUI
 * Copyright (c) 2024-present ObjectStack Inc.
 *
 * Generates a Service Worker source string with offline support for
 * ObjectUI apps. The output is intended to be written to a file at the
 * web root (e.g. `/service-worker.js`) by the application's build
 * pipeline; it is *not* shipped at runtime by the mobile package itself.
 *
 * The generated SW does three things:
 *  1. Caches the application shell on install (`cache-first` strategy).
 *  2. Falls back to network-first for API calls, so reads are fresh
 *     when online and degrade to cached responses when offline.
 *  3. Listens for `sync` events with tag `objectui-offline-queue` and
 *     posts a `REPLAY_QUEUE` message to all clients so the running
 *     pages can flush their queues from the foreground.
 */

export interface ServiceWorkerSourceOptions {
  /** Cache name; bump to invalidate on deploy. */
  cacheName?: string;
  /** Application shell URLs to pre-cache on install. */
  precache?: string[];
  /** URL prefix that identifies API requests (network-first). */
  apiPrefix?: string;
  /** Background-sync tag name. */
  syncTag?: string;
}

/**
 * Build a Service Worker JavaScript source string. Customize the cache
 * version, app shell, and sync tag via `options`.
 */
export function getServiceWorkerSource(options: ServiceWorkerSourceOptions = {}): string {
  const cacheName = options.cacheName ?? 'objectui-shell-v1';
  const precache = options.precache ?? ['/', '/index.html'];
  const apiPrefix = options.apiPrefix ?? '/api/';
  const syncTag = options.syncTag ?? 'objectui-offline-queue';

  return `// Auto-generated by @object-ui/mobile getServiceWorkerSource()
const CACHE = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(precache)};
const API_PREFIX = ${JSON.stringify(apiPrefix)};
const SYNC_TAG = ${JSON.stringify(syncTag)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
    ),
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  if (url.pathname.startsWith(API_PREFIX)) {
    // Network-first for API
    event.respondWith(
      fetch(req).then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
        return res;
      }).catch(() => caches.match(req).then((cached) => cached || Response.error())),
    );
    return;
  }

  // Cache-first for shell assets
  event.respondWith(
    caches.match(req).then((cached) => cached || fetch(req).then((res) => {
      const copy = res.clone();
      caches.open(CACHE).then((c) => c.put(req, copy));
      return res;
    })),
  );
});

self.addEventListener('sync', (event) => {
  if (event.tag !== SYNC_TAG) return;
  event.waitUntil((async () => {
    const all = await self.clients.matchAll({ includeUncontrolled: true });
    for (const client of all) {
      client.postMessage({ type: 'REPLAY_QUEUE', tag: SYNC_TAG });
    }
  })());
});
`;
}

/**
 * Request a one-shot background sync. The page should call this after
 * enqueuing offline work so the browser will wake the SW when the
 * connection returns. Returns false if Background Sync is unsupported.
 */
export async function requestBackgroundSync(tag = 'objectui-offline-queue'): Promise<boolean> {
  if (typeof navigator === 'undefined') return false;
  const reg: any = await (navigator as any).serviceWorker?.ready;
  if (!reg || !reg.sync) return false;
  try { await reg.sync.register(tag); return true; } catch { return false; }
}
